server:
  port: 5002

productos:
  api:
    base-url: ${PRODUCTOS_API_BASE_URL:http://localhost:5001}

spring:
  application:
    name: ordenes
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
